Repository leilafarsani/To-Do-List-Group-Work, pull requests merged in 2023-06, with the labels that each got.

#6 Add "Todo" Model (Prisma)
  app/api/todos/route.ts
  app/databasetest/ClientComponent.tsx
  app/databasetest/DatabaseTestPage.module.css
  app/databasetest/ServerComponent.tsx
  app/databasetest/ToDoCard.module.css
  app/databasetest/ToDoCard.tsx
  app/databasetest/ToDoList.module.css
  app/databasetest/page.tsx
  app/databasetest/timestampformatter.ts
  app/libs/prisma.ts
  next.config.js
  prisma/schema.prisma
Labels: enhancement

#11 #10-fix-timestampFormatter-parameter-type
  app/databasetest/timestampformatter.ts
Labels: bug

#21 18-update-typescript-and-types-react-to-latest
  app/databasetest/page.tsx
  package-lock.json
  package.json
Labels: bug, enhancement
